/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2020-12-09 11:03:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Guest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class guest_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>방명록 작성</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheet.css\">\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction send() {\r\n");
      out.write("\t\tif (guest.name.value == \"\") {\r\n");
      out.write("\t\t\talert(\"입력이 안됨\");\r\n");
      out.write("\t\t\tguest.name.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (guest.subject.value == \"\") {\r\n");
      out.write("\t\t\talert(\"제목이 없음\");\r\n");
      out.write("\t\t\tguest.subject.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (guest.contents.value == \"\") {\r\n");
      out.write("\t\t\talert(\"내용이 없음\");\r\n");
      out.write("\t\t\tguest.contents.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tguest.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction clear1() {\r\n");
      out.write("\t\tguest.name.value = \"\";\r\n");
      out.write("\t\t<!--guest.reset();\r\n");
      out.write("\t\t-->\r\n");
      out.write("\t\tguest.name.focus();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body topmargin=\"0\" leftmargin=\"0\">\r\n");
      out.write("\t<table border=\"0\" width=\"800\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"20%\" height=\"500\" bgcolor=\"#ecf1ef\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<!-- 다음에 추가할 부분 -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"80%\" valign=\"top\">&nbsp;<br> <img\r\n");
      out.write("\t\t\t\tsrc=\"./img/bullet-01.gif\"><font size=\"3\" face=\"돋움\"\r\n");
      out.write("\t\t\t\tcolor=\"blue\"> <b>방명록</b></font> <font size=\"2\"> - 글쓰기</font>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<img src=\"./img/bullet-03.gif\"><font size=\"2\" face=\"돋움\"\r\n");
      out.write("\t\t\t\t\t\tcolor=\"orange\"> 잠깐</font> &nbsp; <img src=\"./img/bullet-02.gif\"><font\r\n");
      out.write("\t\t\t\t\t\tsize=\"2\" face=\"돋움\">는 필수 입력 사항입니다.</font>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t<form method=\"post\" name=\"guest\" action=\"/guest_write\">\r\n");
      out.write("\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"5%\" align=\"right\"><img src=\"./img/bullet-02.gif\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"15%\"><font size=\"2\" face=\"돋움\">글쓴이</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"80%\"><input type=\"text\" size=\"20\" name=\"name\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\"><img src=\"./img/bullet-02.gif\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font size=\"2\" face=\"돋움\">제목</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" size=\"60\" name=\"subject\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\"><img src=\"./img/bullet-02.gif\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font size=\"2\" face=\"돋움\">내용</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><textarea wrap=\"physical\" rows=\"10\" name=\"contents\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcols=\"60\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font size=\"2\">&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"button\" value=\"전송하기\" onClick=\"send()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"취소\" onClick=\"clear1()\"> <!--\r\n");
      out.write("                     <a href=\"javascript:send()\">◀등 록▶</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                     <a href=\"javascript:history.go(-1)\">◀취 소▶</a>\r\n");
      out.write("                     --></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
